'use strict';
// Built-in word lists seeded into the DB on first run.
// Format: { name, grade_level, words: [{word, level}] }

const BUILT_IN = [
  {
    name: 'Level 1 — CVC & Sight Words',
    grade_level: 1,
    words: [
      // CVC words
      {word:'cat',level:1},{word:'dog',level:1},{word:'big',level:1},{word:'run',level:1},
      {word:'sit',level:1},{word:'top',level:1},{word:'cup',level:1},{word:'hat',level:1},
      {word:'bed',level:1},{word:'sun',level:1},{word:'red',level:1},{word:'map',level:1},
      {word:'leg',level:1},{word:'pig',level:1},{word:'box',level:1},{word:'fun',level:1},
      {word:'hen',level:1},{word:'van',level:1},{word:'web',level:1},{word:'can',level:1},
      {word:'dad',level:1},{word:'man',level:1},{word:'pan',level:1},{word:'fan',level:1},
      {word:'bin',level:1},{word:'pin',level:1},{word:'tin',level:1},{word:'win',level:1},
      {word:'fog',level:1},{word:'log',level:1},{word:'bug',level:1},{word:'mug',level:1},
      // Basic sight words
      {word:'the',level:1},{word:'and',level:1},{word:'was',level:1},{word:'for',level:1},
      {word:'are',level:1},{word:'but',level:1},{word:'not',level:1},{word:'you',level:1},
      {word:'all',level:1},{word:'can',level:1},{word:'had',level:1},{word:'her',level:1},
      {word:'his',level:1},{word:'him',level:1},{word:'she',level:1},{word:'one',level:1},
      {word:'our',level:1},{word:'out',level:1},{word:'has',level:1},{word:'him',level:1},
    ],
  },
  {
    name: 'Level 2 — Blends & Digraphs',
    grade_level: 2,
    words: [
      // Blends
      {word:'frog',level:2},{word:'play',level:2},{word:'best',level:2},{word:'club',level:2},
      {word:'drop',level:2},{word:'flag',level:2},{word:'glad',level:2},{word:'grip',level:2},
      {word:'plan',level:2},{word:'skin',level:2},{word:'slug',level:2},{word:'snap',level:2},
      {word:'spin',level:2},{word:'step',level:2},{word:'swim',level:2},{word:'trip',level:2},
      {word:'from',level:2},{word:'just',level:2},{word:'much',level:2},{word:'such',level:2},
      {word:'flat',level:2},{word:'clap',level:2},{word:'drip',level:2},{word:'grin',level:2},
      // Digraphs
      {word:'ship',level:2},{word:'chat',level:2},{word:'thin',level:2},{word:'when',level:2},
      {word:'then',level:2},{word:'shop',level:2},{word:'chip',level:2},{word:'chop',level:2},
      {word:'that',level:2},{word:'this',level:2},{word:'with',level:2},{word:'them',level:2},
      {word:'dish',level:2},{word:'fish',level:2},{word:'rich',level:2},{word:'rush',level:2},
      {word:'bush',level:2},{word:'cash',level:2},{word:'dash',level:2},{word:'wish',level:2},
    ],
  },
  {
    name: 'Level 3 — Long Vowels & Patterns',
    grade_level: 3,
    words: [
      // Silent-e long vowels
      {word:'make',level:3},{word:'bike',level:3},{word:'home',level:3},{word:'cube',level:3},
      {word:'late',level:3},{word:'mine',level:3},{word:'note',level:3},{word:'cute',level:3},
      {word:'game',level:3},{word:'pine',level:3},{word:'pole',level:3},{word:'tune',level:3},
      {word:'wave',level:3},{word:'hole',level:3},{word:'came',level:3},{word:'fame',level:3},
      {word:'lane',level:3},{word:'lime',level:3},{word:'nose',level:3},{word:'rose',level:3},
      {word:'bone',level:3},{word:'cone',level:3},{word:'cane',level:3},{word:'cape',level:3},
      {word:'cave',level:3},{word:'dive',level:3},{word:'fire',level:3},{word:'nice',level:3},
      {word:'side',level:3},{word:'tide',level:3},{word:'wide',level:3},{word:'bride',level:3},
      {word:'drive',level:3},{word:'glide',level:3},{word:'grade',level:3},{word:'grape',level:3},
      // Vowel teams
      {word:'rain',level:3},{word:'tail',level:3},{word:'road',level:3},{word:'coat',level:3},
      {word:'beat',level:3},{word:'seal',level:3},{word:'feet',level:3},{word:'seed',level:3},
    ],
  },
  {
    name: 'Level 4 — Multisyllabic Words',
    grade_level: 4,
    words: [
      {word:'running',level:4},{word:'stopping',level:4},{word:'farmer',level:4},
      {word:'before',level:4},{word:'always',level:4},{word:'around',level:4},
      {word:'number',level:4},{word:'under',level:4},{word:'water',level:4},
      {word:'together',level:4},{word:'something',level:4},{word:'nothing',level:4},
      {word:'better',level:4},{word:'letter',level:4},{word:'butter',level:4},
      {word:'sister',level:4},{word:'brother',level:4},{word:'mother',level:4},
      {word:'father',level:4},{word:'finger',level:4},{word:'winter',level:4},
      {word:'summer',level:4},{word:'garden',level:4},{word:'window',level:4},
      {word:'happen',level:4},{word:'dinner',level:4},{word:'chicken',level:4},
      {word:'basket',level:4},{word:'pocket',level:4},{word:'ticket',level:4},
      {word:'blanket',level:4},{word:'carpet',level:4},{word:'forest',level:4},
      {word:'corner',level:4},{word:'center',level:4},{word:'spider',level:4},
      {word:'perfect',level:4},{word:'problem',level:4},{word:'people',level:4},
      {word:'children',level:4},{word:'kitchen',level:4},{word:'million',level:4},
    ],
  },
  {
    name: 'Level 5 — Vocabulary & Suffixes',
    grade_level: 5,
    words: [
      {word:'nation',level:5},{word:'station',level:5},{word:'action',level:5},
      {word:'question',level:5},{word:'section',level:5},{word:'mention',level:5},
      {word:'attention',level:5},{word:'vacation',level:5},{word:'direction',level:5},
      {word:'education',level:5},{word:'information',level:5},{word:'position',level:5},
      {word:'library',level:5},{word:'nature',level:5},{word:'future',level:5},
      {word:'picture',level:5},{word:'creature',level:5},{word:'furniture',level:5},
      {word:'treasure',level:5},{word:'measure',level:5},{word:'pleasure',level:5},
      {word:'important',level:5},{word:'different',level:5},{word:'difficult',level:5},
      {word:'beautiful',level:5},{word:'wonderful',level:5},{word:'powerful',level:5},
      {word:'dangerous',level:5},{word:'colorful',level:5},{word:'careful',level:5},
      {word:'possible',level:5},{word:'terrible',level:5},{word:'horrible',level:5},
      {word:'opposite',level:5},{word:'medicine',level:5},{word:'describe',level:5},
      {word:'practice',level:5},{word:'prepare',level:5},{word:'because',level:5},
      {word:'believe',level:5},{word:'friend',level:5},{word:'people',level:5},
    ],
  },
  {
    name: 'Level 6 — Academic Vocabulary',
    grade_level: 6,
    words: [
      {word:'necessary',level:6},{word:'separate',level:6},{word:'receive',level:6},
      {word:'definitely',level:6},{word:'february',level:6},{word:'wednesday',level:6},
      {word:'environment',level:6},{word:'government',level:6},{word:'immediately',level:6},
      {word:'occasion',level:6},{word:'privilege',level:6},{word:'recommend',level:6},
      {word:'embarrass',level:6},{word:'exaggerate',level:6},{word:'guarantee',level:6},
      {word:'independent',level:6},{word:'maintenance',level:6},{word:'occurrence',level:6},
      {word:'beginning',level:6},{word:'calendar',level:6},{word:'business',level:6},
      {word:'mischievous',level:6},{word:'rhythm',level:6},{word:'schedule',level:6},
      {word:'successful',level:6},{word:'tomorrow',level:6},{word:'until',level:6},
      {word:'vacuum',level:6},{word:'knowledge',level:6},{word:'grammar',level:6},
      {word:'neighbor',level:6},{word:'surprise',level:6},{word:'relevant',level:6},
      {word:'restaurant',level:6},{word:'conscience',level:6},{word:'lieutenant',level:6},
      {word:'maneuver',level:6},{word:'bureaucracy',level:6},{word:'miscellaneous',level:6},
    ],
  },
  {
    name: 'Level 7 — Regional Spelling Bee',
    grade_level: 7,
    words: [
      {word:'entrepreneur',level:7},{word:'catastrophe',level:7},{word:'camouflage',level:7},
      {word:'silhouette',level:7},{word:'pharaoh',level:7},{word:'pneumonia',level:7},
      {word:'sergeant',level:7},{word:'millennium',level:7},{word:'metamorphosis',level:7},
      {word:'exquisite',level:7},{word:'sophisticated',level:7},{word:'perseverance',level:7},
      {word:'fluorescent',level:7},{word:'acquaintance',level:7},{word:'Mediterranean',level:7},
      {word:'surveillance',level:7},{word:'extraordinary',level:7},{word:'precipitation',level:7},
      {word:'choreography',level:7},{word:'flamboyant',level:7},{word:'conscientious',level:7},
      {word:'mnemonic',level:7},{word:'accommodate',level:7},{word:'dilapidated',level:7},
      {word:'phosphorescent',level:7},{word:'rendezvous',level:7},{word:'assassination',level:7},
      {word:'philanthropy',level:7},{word:'archaeology',level:7},{word:'benevolent',level:7},
    ],
  },
  {
    name: 'Level 8 — State Spelling Bee',
    grade_level: 8,
    words: [
      {word:'camaraderie',level:8},{word:'ephemeral',level:8},{word:'perspicacious',level:8},
      {word:'idiosyncrasy',level:8},{word:'soliloquy',level:8},{word:'omniscient',level:8},
      {word:'ubiquitous',level:8},{word:'clandestine',level:8},{word:'serendipity',level:8},
      {word:'magnanimous',level:8},{word:'obsequious',level:8},{word:'sagacious',level:8},
      {word:'recalcitrant',level:8},{word:'acquiesce',level:8},{word:'mercurial',level:8},
      {word:'quintessential',level:8},{word:'loquacious',level:8},{word:'pedantic',level:8},
      {word:'sycophant',level:8},{word:'labyrinthine',level:8},{word:'perfidious',level:8},
      {word:'equivocate',level:8},{word:'nonchalant',level:8},{word:'gregarious',level:8},
      {word:'ebullient',level:8},{word:'tenacious',level:8},{word:'obfuscate',level:8},
      {word:'circumlocution',level:8},{word:'trepidation',level:8},{word:'prestidigitation',level:8},
    ],
  },
  {
    name: 'Level 9 — National Spelling Bee',
    grade_level: 9,
    words: [
      {word:'onomatopoeia',level:9},{word:'archipelago',level:9},{word:'pejorative',level:9},
      {word:'verisimilitude',level:9},{word:'impresario',level:9},{word:'connoisseur',level:9},
      {word:'maelstrom',level:9},{word:'quixotic',level:9},{word:'zeitgeist',level:9},
      {word:'chiaroscuro',level:9},{word:'schadenfreude',level:9},{word:'sommelier',level:9},
      {word:'bougainvillea',level:9},{word:'hegemony',level:9},{word:'kaleidoscope',level:9},
      {word:'renaissance',level:9},{word:'palindrome',level:9},{word:'haberdasher',level:9},
      {word:'fiduciary',level:9},{word:'diaphanous',level:9},{word:'ecclesiastical',level:9},
      {word:'perspicacity',level:9},{word:'legerdemain',level:9},{word:'sesquipedalian',level:9},
      {word:'tergiversation',level:9},
    ],
  },
  {
    name: 'Level 10 — Championship',
    grade_level: 10,
    words: [
      {word:'cymotrichous',level:10},{word:'feuilleton',level:10},{word:'succedaneum',level:10},
      {word:'guerdon',level:10},{word:'appoggiatura',level:10},{word:'syzygy',level:10},
      {word:'stichomythia',level:10},{word:'logorrhea',level:10},{word:'quincunx',level:10},
      {word:'anagnorisis',level:10},{word:'plenipotentiary',level:10},{word:'weltanschauung',level:10},
      {word:'sternutation',level:10},{word:'amphigory',level:10},{word:'noctambulism',level:10},
      {word:'knaidel',level:10},{word:'covellite',level:10},{word:'psammophile',level:10},
      {word:'ursprache',level:10},{word:'schwarmerei',level:10},
    ],
  },
];

module.exports = { BUILT_IN };
