'use strict';
// Weekly word lists organized by grade and theme.
// Format: { grade, week, theme, words: [string] }

const WEEKLY = [

// ══════════════════════════════════════════════════════
// GRADE 1  (6 words/week, 30 weeks)
// ══════════════════════════════════════════════════════

{ grade:1, week:1,  theme:'Short A (CVC)',         words:['cat','bat','hat','mat','rat','sat'] },
{ grade:1, week:2,  theme:'Short E (CVC)',          words:['bed','red','fed','led','wed','pet'] },
{ grade:1, week:3,  theme:'Short I (CVC)',          words:['big','dig','fig','pig','rig','wig'] },
{ grade:1, week:4,  theme:'Short O (CVC)',          words:['box','fox','hot','lot','top','hop'] },
{ grade:1, week:5,  theme:'Short U (CVC)',          words:['bug','hug','mug','rug','tug','pup'] },
{ grade:1, week:6,  theme:'Sight Words Set 1',      words:['the','and','is','in','it','on'] },
{ grade:1, week:7,  theme:'Sight Words Set 2',      words:['are','you','was','for','not','but'] },
{ grade:1, week:8,  theme:'Short A Families -an',   words:['can','fan','man','pan','ran','tan'] },
{ grade:1, week:9,  theme:'Short A Families -at',   words:['bat','cat','fat','hat','mat','sat'] },
{ grade:1, week:10, theme:'Short I Families -in',   words:['bin','fin','kin','pin','tin','win'] },
{ grade:1, week:11, theme:'Short I Families -it',   words:['bit','fit','hit','kit','sit','wit'] },
{ grade:1, week:12, theme:'Short O Families -og',   words:['bog','dog','fog','hog','jog','log'] },
{ grade:1, week:13, theme:'Short U Families -un',   words:['bun','fun','gun','nun','run','sun'] },
{ grade:1, week:14, theme:'Consonant Blends -l',    words:['flag','flat','flip','flog','plan','play'] },
{ grade:1, week:15, theme:'Consonant Blends -r',    words:['crab','drip','drop','frog','grab','grip'] },
{ grade:1, week:16, theme:'Consonant Blends -s',    words:['skip','skin','slim','slip','snap','spin'] },
{ grade:1, week:17, theme:'End Blends -st -nd',     words:['best','fast','fist','last','sand','send'] },
{ grade:1, week:18, theme:'Digraphs sh ch',         words:['chin','chip','shed','ship','shop','shut'] },
{ grade:1, week:19, theme:'Digraphs th wh',         words:['that','them','thin','this','when','whip'] },
{ grade:1, week:20, theme:'Long A (silent e)',       words:['cake','came','cape','gate','lane','name'] },
{ grade:1, week:21, theme:'Long I (silent e)',       words:['bike','bite','dime','fire','hide','like'] },
{ grade:1, week:22, theme:'Long O (silent e)',       words:['bone','code','home','hole','mole','note'] },
{ grade:1, week:23, theme:'Long U (silent e)',       words:['cube','cute','dune','fuse','mule','tune'] },
{ grade:1, week:24, theme:'Long E (ee ea)',          words:['bee','feel','heat','meet','seal','seed'] },
{ grade:1, week:25, theme:'Digraph ck',             words:['back','black','block','click','duck','kick'] },
{ grade:1, week:26, theme:'-ing endings',           words:['digging','hitting','jumping','running','sitting','winning'] },
{ grade:1, week:27, theme:'-ed endings',            words:['helped','jumped','looked','played','talked','walked'] },
{ grade:1, week:28, theme:'Compound Words',         words:['cupcake','hotdog','into','upon','cannot','inside'] },
{ grade:1, week:29, theme:'Color Words',            words:['black','blue','brown','green','white','yellow'] },
{ grade:1, week:30, theme:'Number Words',           words:['five','four','nine','one','seven','three'] },

// ══════════════════════════════════════════════════════
// GRADE 2  (12–14 words/week, 30 weeks)
// Source: mv.org Harcourt curriculum + Spelling Bee words slotted by theme
// ══════════════════════════════════════════════════════

{ grade:2, week:1,  theme:'Short Vowels Review',
  words:['best','blend','clap','fast','fist','gust','lamp','limp','stomp','swim','trust','cramp'] },
{ grade:2, week:2,  theme:'Long A (ai ay)',
  words:['bail','brain','chain','claim','grain','plain','rail','sail','snail','spray','stain','train'] },
{ grade:2, week:3,  theme:'Long E (ee ea)',
  words:['beach','clean','dream','feast','flea','greet','kneel','leash','please','reach','speak','steam'] },
{ grade:2, week:4,  theme:'Long I (ie igh)',
  words:['bright','fight','fright','knight','light','might','night','right','sight','slight','tight','tried'] },
{ grade:2, week:5,  theme:'Long O (oa ow)',
  words:['below','boat','bowl','cloak','crow','elbow','float','flow','glow','groan','known','throat'] },
{ grade:2, week:6,  theme:'Long U (ue oo)',
  words:['bloom','booth','clue','cruel','drool','flute','gloom','prune','proof','rude','spoon','true'] },
{ grade:2, week:7,  theme:'R-Controlled ar or',
  words:['barn','born','card','cart','chord','cord','fork','form','hard','harm','porch','yard'] },
{ grade:2, week:8,  theme:'R-Controlled er ir ur',
  words:['bird','blur','burn','clerk','curl','dirt','first','furry','hurt','perch','shirt','skirt'] },
{ grade:2, week:9,  theme:'Diphthongs oi oy',
  words:['avoid','boil','broil','choice','coil','enjoy','loyal','moist','noise','point','royal','voice'] },
{ grade:2, week:10, theme:'Diphthongs ou ow',
  words:['amount','bound','brown','cloud','count','crowd','flour','found','ground','mouth','proud','scout'] },
{ grade:2, week:11, theme:'Consonant Blends Review',
  words:['clench','clump','crunch','drench','dwell','flinch','flung','front','grudge','plump','shrink','slung'] },
{ grade:2, week:12, theme:'Silent Letters (kn wr gn)',
  words:['gnarl','gnome','knack','kneel','knife','knight','knit','knock','knot','wrap','wren','wrong'] },
{ grade:2, week:13, theme:'Soft c and g',
  words:['age','cage','cent','chance','dance','fence','force','gel','germ','grace','hedge','lace'] },
{ grade:2, week:14, theme:'-tion -sion endings',
  words:['action','caution','fusion','mansion','mention','mission','motion','nation','portion','season','station','vision'] },
{ grade:2, week:15, theme:'Prefixes un- re-',
  words:['recheck','refill','reheat','remind','reopen','repack','unable','unclear','uneven','unkind','unlock','unwrap'] },
{ grade:2, week:16, theme:'Suffixes -ful -less',
  words:['careful','fearful','graceful','grateful','harmful','helpful','hopeless','joyful','painless','peaceful','thankful','useless'] },
{ grade:2, week:17, theme:'Plurals (-s -es -ies)',
  words:['beaches','berries','boxes','brushes','bunches','cherries','cities','classes','countries','flies','stories','switches'] },
{ grade:2, week:18, theme:'Compound Words',
  words:['backyard','bedroom','butterfly','campfire','doorbell','flashlight','football','greenhouse','notebook','outside','rainbow','sunflower'] },
{ grade:2, week:19, theme:'Contractions',
  words:["can't","couldn't","didn't","don't","hadn't","hasn't","haven't","isn't","it's","she'll","they're","won't"] },
{ grade:2, week:20, theme:'Homophones',
  words:['aunt','bear','blew','fair','flour','hair','hear','here','knot','not','pear','sale'] },
{ grade:2, week:21, theme:'Double Consonants',
  words:['allow','arrow','bottom','butter','buzzing','cancel','dripping','happen','little','mitten','pepper','rabbit'] },
{ grade:2, week:22, theme:'Words With -ck -ng -nk',
  words:['blank','blank','brick','drink','honk','ink','knock','pink','rank','shrink','sink','track'] },
{ grade:2, week:23, theme:'Three-Letter Blends spl spr str',
  words:['spread','spring','sprint','sprout','string','stripe','strong','struck','struggle','splash','split','spray'] },
{ grade:2, week:24, theme:'Words Ending -le',
  words:['able','apple','bottle','bubble','cable','cradle','eagle','fable','giggle','handle','little','purple'] },
{ grade:2, week:25, theme:'Academic Vocabulary — School',
  words:['author','chapter','describe','discuss','explain','journal','lesson','library','paragraph','project','report','research'] },
{ grade:2, week:26, theme:'Science Words — Animals',
  words:['amphibian','burrow','carnivore','habitat','herbivore','hibernate','insect','mammal','migrate','predator','reptile','survive'] },
{ grade:2, week:27, theme:'Science Words — Plants & Weather',
  words:['blossom','climate','drought','erosion','evaporate','forecast','meadow','moisture','pollen','roots','sprout','stem'] },
{ grade:2, week:28, theme:'Social Studies — Community',
  words:['citizen','community','council','county','government','mayor','neighbor','republic','resource','service','tradition','volunteer'] },
{ grade:2, week:29, theme:'Math & Measurement Words',
  words:['calculate','centimeter','diameter','estimate','fraction','gallon','kilogram','kilometer','measure','multiply','perimeter','subtract'] },
{ grade:2, week:30, theme:'Spelling Bee Challenge — Grade 2',
  words:['bouquet','canyon','cinnamon','colonel','curious','February','hungry','jealous','language','library','people','rhythm'] },

// ══════════════════════════════════════════════════════
// GRADE 3  (14 words/week, 30 weeks)
// Morphological patterns
// ══════════════════════════════════════════════════════

{ grade:3, week:1,  theme:'Root Words — Short Review',
  words:['act','add','base','claim','close','form','help','hold','move','pass','play','reach','safe','turn'] },
{ grade:3, week:2,  theme:'Prefix un-',
  words:['uncertain','uncommon','uncomfortable','uncover','unfair','unfamiliar','unhappy','unlikely','unnecessary','unpack','untie','unusual','unwilling','upset'] },
{ grade:3, week:3,  theme:'Prefix re-',
  words:['rebuild','recall','reclaim','recycle','redefine','redo','refine','reform','refresh','regain','replace','represent','restate','reuse'] },
{ grade:3, week:4,  theme:'Prefix dis- mis-',
  words:['disable','disagree','disappear','disbelief','discard','discover','dismiss','disobey','disorder','display','miscount','mislead','misspell','mistake'] },
{ grade:3, week:5,  theme:'Prefix pre- pro-',
  words:['predict','prepare','present','preview','prevent','preheat','prefix','produce','progress','project','protect','provide','protest','proven'] },
{ grade:3, week:6,  theme:'Suffix -ful -less',
  words:['cheerful','colorful','fearless','graceful','grateful','harmful','helpless','hopeful','joyful','mindless','peaceful','powerful','restless','thankful'] },
{ grade:3, week:7,  theme:'Suffix -ment -ness',
  words:['agreement','boldness','darkness','enjoyment','fairness','goodness','government','happiness','movement','openness','payment','sadness','softness','treatment'] },
{ grade:3, week:8,  theme:'Suffix -er -est (comparatives)',
  words:['brighter','bravest','colder','coolest','darker','fastest','friendlier','greater','happiest','kindest','louder','sharper','slowest','stronger'] },
{ grade:3, week:9,  theme:'Suffix -ing -ed (inflections)',
  words:['baking','carrying','clapped','dragged','dripping','flipped','grabbed','hopping','planning','shipped','skipped','swimming','trapped','wrapped'] },
{ grade:3, week:10, theme:'Suffix -tion -sion',
  words:['action','caption','caution','collection','description','direction','election','expression','fiction','mention','motion','nation','permission','solution'] },
{ grade:3, week:11, theme:'Suffix -able -ible',
  words:['adorable','affordable','available','believable','breakable','capable','comfortable','dependable','enjoyable','lovable','possible','reliable','responsible','valuable'] },
{ grade:3, week:12, theme:'Suffix -ly (adverbs)',
  words:['bravely','briefly','carefully','clearly','closely','completely','easily','finally','gladly','kindly','loudly','nearly','quickly','safely'] },
{ grade:3, week:13, theme:'Latin Root port (carry)',
  words:['export','import','portable','portage','porter','portfolio','portly','transport','airport','rapport','report','support','deport','important'] },
{ grade:3, week:14, theme:'Latin Root duct duc (lead)',
  words:['abduct','conduct','deduce','duct','educate','induct','introduce','produce','product','reduce','reproduce','seduce','viaduct','deduction'] },
{ grade:3, week:15, theme:'Latin Root scrib scribe (write)',
  words:['ascribe','circumscribe','describe','inscribe','manuscript','postscript','prescribe','script','scripture','subscribe','transcribe','description','prescription','subscriber'] },
{ grade:3, week:16, theme:'Latin Root vis vid (see)',
  words:['evidence','invisible','provide','revise','supervise','video','visa','visible','vision','visit','visitor','vista','visor','visualize'] },
{ grade:3, week:17, theme:'Latin Root aud (hear)',
  words:['audible','audience','audio','auditorium','auditory','audiobook','inaudible','audit','auditor','ovation','audiovisual','audition','audacity','acclaim'] },
{ grade:3, week:18, theme:'Greek Root graph (write)',
  words:['autograph','biography','geography','graph','graphic','paragraph','photograph','phonograph','telegraph','topography','seismograph','choreograph','demography','lithograph'] },
{ grade:3, week:19, theme:'Greek Root phon (sound)',
  words:['earphone','homophone','microphone','phone','phonics','phonogram','saxophone','symphony','telephone','xylophone','euphony','cacophony','polyphony','aphonia'] },
{ grade:3, week:20, theme:'Greek Root bio (life)',
  words:['antibiotic','autobiography','biodegradable','biography','biology','biopsy','biosphere','biotechnology','microbe','microbiome','symbiosis','amphibian','aerobics','biome'] },
{ grade:3, week:21, theme:'Compound Words — Nature',
  words:['bluebird','butterfly','cattail','dragonfly','earthquake','firefly','grasshopper','honeybee','rainforest','redwood','seashell','snowflake','sunflower','waterfall'] },
{ grade:3, week:22, theme:'Homophones & Homographs',
  words:['allowed','aloud','bare','bear','brake','break','ceiling','coarse','course','deer','dear','fair','fare','knight'] },
{ grade:3, week:23, theme:'Possessives & Apostrophes',
  words:["America's","children's","class's","doctor's","everyone's","family's","men's","mother's","people's","school's","student's","teacher's","women's","year's"] },
{ grade:3, week:24, theme:'Words From Spanish',
  words:['adobe','avocado','bronco','canyon','cargo','lasso','mosquito','mustang','patio','plaza','ranch','rodeo','salsa','tornado'] },
{ grade:3, week:25, theme:'Words From French',
  words:['ballet','bouquet','bureau','café','chef','chic','debut','depot','genre','gourmet','palette','plateau','silhouette','unique'] },
{ grade:3, week:26, theme:'Science — Life Science',
  words:['adaptation','camouflage','chlorophyll','ecosystem','environment','evolution','extinct','fertilize','germinate','hibernate','organism','photosynthesis','predator','reproduce'] },
{ grade:3, week:27, theme:'Science — Earth & Space',
  words:['asteroid','atmosphere','constellation','crescent','eclipse','erosion','gravity','hemisphere','meteor','mineral','orbit','precipitation','telescope','volcano'] },
{ grade:3, week:28, theme:'Social Studies — Government & History',
  words:['amendment','civilization','colony','constitution','democracy','document','independence','legislature','liberty','patriot','republic','revolution','sovereignty','tradition'] },
{ grade:3, week:29, theme:'Math — Operations & Fractions',
  words:['circumference','denominator','diameter','dividend','divisor','equation','equivalent','estimate','numerator','perimeter','quotient','remainder','subtrahend','variable'] },
{ grade:3, week:30, theme:'Spelling Bee Challenge — Grade 3',
  words:['appreciate','coincidence','convenience','curiosity','embarrass','forfeit','guarantee','humorous','immediately','lieutenant','mischievous','necessary','privilege','sergeant'] },

// ══════════════════════════════════════════════════════
// GRADE 4  (16 words/week, 30 weeks)
// Latin & Greek roots + content-area vocabulary
// ══════════════════════════════════════════════════════

{ grade:4, week:1,  theme:'Latin Root rupt (break)',
  words:['abrupt','bankrupt','corrupt','disrupt','erupt','eruption','interrupt','irrupt','rupture','abruptly','corrupted','disruption','eruption','interrupt','irruptive','bankrupt'] },
{ grade:4, week:2,  theme:'Latin Root struct (build)',
  words:['construct','construction','destroy','destruct','infrastructure','instruct','instruction','instructor','obstruct','reconstruct','restructure','structure','structural','constrain','stricture','abstract'] },
{ grade:4, week:3,  theme:'Latin Root spect spec (look)',
  words:['aspect','circumspect','expect','inspect','inspection','inspector','introspect','perspective','prospect','prospective','respect','retrospect','spectacle','spectator','spectacular','spectrum'] },
{ grade:4, week:4,  theme:'Latin Root tract (pull)',
  words:['abstract','attract','attraction','contract','detract','distract','distraction','extract','protract','retract','subtract','traction','tractor','distract','intractable','attractive'] },
{ grade:4, week:5,  theme:'Latin Root ten tent (hold)',
  words:['abstain','contain','content','continent','detain','extent','maintain','obtain','retain','sustain','tenacity','tenant','tenet','tenure','attention','intention'] },
{ grade:4, week:6,  theme:'Latin Root mit miss (send)',
  words:['admit','commit','dismiss','emit','intermission','mission','omit','permit','promise','remit','submit','transmit','admission','commission','compromise','emission'] },
{ grade:4, week:7,  theme:'Greek Root astro aster (star)',
  words:['asterisk','asteroid','astrology','astronaut','astronomer','astronomy','astrophysics','astral','stellar','constellation','celestial','planetary','galaxy','nebula','cosmos','solar'] },
{ grade:4, week:8,  theme:'Greek Root geo (earth)',
  words:['geography','geology','geometry','geophysics','geosphere','geothermal','geocentric','geode','geodesic','geometric','geostationary','geotag','geography','regional','terrain','topography'] },
{ grade:4, week:9,  theme:'Greek Root micro macro (small/large)',
  words:['macroeconomics','macrobiotic','macroscopic','microbe','microbiology','microchip','microcosm','micrometer','microorganism','microphone','microscope','microscopic','microwave','macrofossil','macrophage','macro'] },
{ grade:4, week:10, theme:'Greek Root tele (far)',
  words:['telegraph','telephone','telescope','television','telecast','teleconference','telekinesis','telepathy','teleport','teleprompter','telethon','telecommute','telemetry','telemedicine','telegram','telephoto'] },
{ grade:4, week:11, theme:'Science — Physical Science',
  words:['acceleration','buoyancy','condensation','conduction','convection','density','friction','gravity','inertia','kinetic','magnetic','momentum','radiation','thermal','velocity','wavelength'] },
{ grade:4, week:12, theme:'Science — Chemistry Basics',
  words:['acid','alkaline','atom','chemical','compound','crystal','dissolve','electron','element','evaporate','hydrogen','ion','molecule','neutron','oxygen','proton'] },
{ grade:4, week:13, theme:'Science — Biology',
  words:['bacteria','cell','chromosome','circulation','digestion','enzyme','genetics','immune','membrane','metabolism','nucleus','organism','protein','respiration','stimulus','tissue'] },
{ grade:4, week:14, theme:'Math — Geometry',
  words:['adjacent','circumference','congruent','cylinder','diameter','hexagon','hypotenuse','isosceles','octagon','parallel','pentagon','perpendicular','polygon','quadrilateral','rhombus','symmetry'] },
{ grade:4, week:15, theme:'Math — Algebra & Data',
  words:['algorithm','coefficient','constant','coordinate','equation','expression','function','inequality','integer','probability','proportion','ratio','sequence','variable','average','median'] },
{ grade:4, week:16, theme:'Social Studies — Ancient Civilizations',
  words:['agriculture','archeology','artifact','civilization','dynasty','emperor','empire','excavate','hieroglyphics','monarchy','mythology','pharaoh','pyramid','ritual','sacrifice','society'] },
{ grade:4, week:17, theme:'Social Studies — American History',
  words:['abolition','amendment','capitalism','colonist','confederation','congress','constitution','democracy','emancipation','frontier','independence','legislation','migration','patriot','republic','territory'] },
{ grade:4, week:18, theme:'Social Studies — Economics',
  words:['bankruptcy','budget','commodity','competition','consumer','currency','demand','economics','entrepreneur','export','import','inflation','investment','manufacturer','monopoly','supply'] },
{ grade:4, week:19, theme:'Language Arts — Literary Terms',
  words:['alliteration','antagonist','characterization','climax','conflict','exposition','foreshadowing','imagery','metaphor','narrator','protagonist','resolution','setting','simile','symbolism','theme'] },
{ grade:4, week:20, theme:'Language Arts — Grammar',
  words:['adjective','adverb','clause','conjunction','definition','demonstrative','gerund','infinitive','modifier','participle','possessive','predicate','pronoun','punctuation','subordinate','superlative'] },
{ grade:4, week:21, theme:'Words From Latin — Law & Government',
  words:['alias','alibi','census','civic','civilian','constitution','counsel','defendant','evidence','jury','justice','legislation','official','plaintiff','senator','verdict'] },
{ grade:4, week:22, theme:'Words From Greek — Arts & Culture',
  words:['aesthetic','archetype','carnival','cathedral','chorus','criterion','drama','episode','harmony','harmony','irony','lyric','metaphor','museum','orchestra','theater'] },
{ grade:4, week:23, theme:'Technology & Computing',
  words:['bandwidth','browser','database','download','firmware','hardware','hyperlink','interface','keyboard','network','operating','processor','protocol','software','upload','wireless'] },
{ grade:4, week:24, theme:'Health & Human Body',
  words:['artery','calcium','cardiovascular','digestion','esophagus','exercise','fracture','immune','nutrient','obesity','pulmonary','respiratory','skeleton','tendon','vaccine','vitamin'] },
{ grade:4, week:25, theme:'Environment & Conservation',
  words:['biodiversity','biosphere','climate','conservation','deforestation','ecology','ecosystem','endangered','extinction','fossil','habitat','pollution','recycle','renewable','sustainable','wildlife'] },
{ grade:4, week:26, theme:'Prefixes over- under- out-',
  words:['overachieve','overestimate','overwhelm','overpower','overreact','underestimate','undermine','outnumber','outperform','outreach','overcome','underrate','overdue','underline','outline','outstanding'] },
{ grade:4, week:27, theme:'Suffixes -ous -ious -eous',
  words:['advantageous','ambiguous','ambitious','anxious','contagious','courageous','ferocious','gorgeous','gracious','humorous','infectious','jealous','mischievous','outrageous','precious','vivacious'] },
{ grade:4, week:28, theme:'Suffixes -ance -ence -ancy -ency',
  words:['abundance','assistance','competence','confidence','deficiency','difference','distance','efficiency','evidence','existence','frequency','importance','independence','instance','patience','resistance'] },
{ grade:4, week:29, theme:'Challenging Multisyllabic Words',
  words:['accompaniment','accomplishment','acknowledgment','advertisement','approximately','comfortable','considerably','determination','disappointment','encouragement','exaggerate','extraordinary','particularly','pronunciation','pronunciation','temperature'] },
{ grade:4, week:30, theme:'Spelling Bee Challenge — Grade 4',
  words:['acquaintance','camouflage','conscientious','exquisite','fluorescent','indispensable','magnanimous','Mediterranean','mnemonic','perseverance','pharaoh','pneumonia','rendezvous','silhouette','surveillance','ubiquitous'] },

// ══════════════════════════════════════════════════════
// GRADE 5  (20 words/week, 30 weeks)
// Content-area and vocational themes
// ══════════════════════════════════════════════════════

{ grade:5, week:1,  theme:'Medical & Health Professions',
  words:['anatomy','antibiotics','cardiovascular','diagnosis','epidemic','hygiene','inflammation','inoculation','medication','neurology','nutrition','orthopedic','paramedic','pathology','pediatrics','pharmacist','physiology','psychiatry','rehabilitation','symptom'] },
{ grade:5, week:2,  theme:'Legal & Justice System',
  words:['acquittal','attorney','circumstance','conviction','counsel','defendant','deliberate','deposition','evidence','felony','indictment','innocent','judiciary','jurisdiction','legality','litigation','plaintiff','prosecution','testimony','verdict'] },
{ grade:5, week:3,  theme:'Engineering & Construction',
  words:['architect','blueprint','cantilever','coefficient','compressive','construction','demolition','diameter','engineering','excavation','foundation','hydraulic','infrastructure','insulation','load-bearing','prototype','reinforced','renovation','structural','tensile'] },
{ grade:5, week:4,  theme:'Financial & Banking',
  words:['accrual','amortization','annuity','arbitrage','asset','collateral','commodity','compound','deficit','depreciation','dividend','equity','expenditure','fiduciary','fiscal','infrastructure','liability','liquidity','mortgage','portfolio'] },
{ grade:5, week:5,  theme:'Environmental Science',
  words:['atmosphere','biodegradable','biosphere','carcinogen','conservation','contamination','deforestation','desalination','ecosystem','emissions','environmental','greenhouse','hydrosphere','lithosphere','nonrenewable','ozone','pesticide','pollution','renewable','sustainability'] },
{ grade:5, week:6,  theme:'Agriculture & Food Systems',
  words:['agricultural','agroforestry','aquaculture','composting','cultivation','fertilization','genetically','greenhouse','herbicide','horticulture','hydroponics','irrigation','livestock','monoculture','organic','permaculture','pesticide','sustainable','transplant','watershed'] },
{ grade:5, week:7,  theme:'Technology & Computer Science',
  words:['algorithm','application','artificial','automation','bandwidth','calibration','encryption','firmware','graphical','hardware','infrastructure','integration','interface','network','operating','peripheral','programming','protocol','simulation','software'] },
{ grade:5, week:8,  theme:'Media & Communications',
  words:['advertisement','audience','broadcast','circulation','commentary','communications','correspondent','credibility','documentary','editorial','journalism','multimedia','narrative','persuasion','photojournalism','publication','rhetoric','satire','transmission','typography'] },
{ grade:5, week:9,  theme:'Architecture & Design',
  words:['aesthetic','architecture','asymmetrical','blueprint','colonnade','contemporary','elevation','facade','floorplan','geometric','industrial','infrastructure','metropolitan','modernism','proportion','renaissance','restoration','sustainable','symmetrical','urban'] },
{ grade:5, week:10, theme:'Transportation & Logistics',
  words:['aerodynamic','autonomous','calibration','commercial','coordinates','destination','distribution','efficiency','fluctuation','freight','infrastructure','international','logistics','navigation','petroleum','procurement','propulsion','regulation','terminal','transportation'] },
{ grade:5, week:11, theme:'History — Renaissance & Exploration',
  words:['cartography','civilization','colonization','conquistador','cosmopolitan','discovery','expedition','exploration','globalization','humanist','imperialism','indigenous','mercantilism','navigation','patronage','perspective','printing','reformation','renaissance','sovereignty'] },
{ grade:5, week:12, theme:'History — Industrial Revolution',
  words:['automation','capitalism','corporation','electricity','emigration','exploitation','factory','imperialism','industrialization','innovation','invention','labor','locomotive','manufacture','mechanization','monopoly','patent','proletariat','urbanization','workforce'] },
{ grade:5, week:13, theme:'History — Modern World',
  words:['activism','appeasement','bureaucracy','capitalism','communism','constitution','democracy','diplomacy','fascism','globalization','humanitarian','imperialism','nationalism','propaganda','recession','referendum','sovereignty','terrorism','totalitarianism','urbanization'] },
{ grade:5, week:14, theme:'Science — Chemistry',
  words:['alkalinity','biochemistry','catalyst','combustion','compound','corrosion','distillation','electrode','electrolysis','filtration','hypothesis','neutralization','oxidation','periodic','precipitation','radioactivity','reactivity','solution','solvent','thermodynamics'] },
{ grade:5, week:15, theme:'Science — Physics',
  words:['acceleration','amplitude','centripetal','conductivity','electromagnetic','frequency','gravitational','insulation','kinetic','magnetic','mechanical','momentum','oscillation','potential','radioactive','refraction','semiconductor','thermal','velocity','wavelength'] },
{ grade:5, week:16, theme:'Science — Earth & Space',
  words:['atmosphere','circumference','constellation','continental','coordinates','equinox','geothermal','gravitational','hemisphere','hypothesis','latitude','longitude','magnetosphere','meteorology','observatory','solstice','stratosphere','subduction','tectonic','topography'] },
{ grade:5, week:17, theme:'Math — Statistics & Probability',
  words:['approximation','arithmetic','coefficient','correlation','denominator','deviation','distribution','equilateral','estimation','exponent','factorial','frequency','geometric','hypothesis','independent','percentage','proportion','quadratic','ratio','variable'] },
{ grade:5, week:18, theme:'Arts — Music & Theater',
  words:['accompaniment','acoustics','arrangement','choreography','chromatic','composition','counterpoint','diminuendo','dramaturgy','flamboyant','improvisation','instrumental','orchestration','percussion','performance','rehearsal','repertoire','sophisticated','syncopation','virtuoso'] },
{ grade:5, week:19, theme:'Arts — Visual Art & Photography',
  words:['abstract','architecture','chiaroscuro','composition','contemporary','contrast','dimensional','exhibition','foreground','horizon','impressionism','juxtaposition','landscape','perspective','photography','portrait','proportion','Renaissance','sculpture','symmetry'] },
{ grade:5, week:20, theme:'World Languages & Cultures',
  words:['anthropology','archipelago','civilization','diplomacy','diversity','ethnography','globalization','humanitarian','indigenous','intercultural','linguistics','migration','multilingual','multicultural','nationalism','perspective','sociology','stereotype','tradition','xenophobia'] },
{ grade:5, week:21, theme:'Latin Prefixes — Number',
  words:['bifocal','bilateral','binary','bipartisan','centennial','centimeter','century','decimal','millennium','monologue','monopoly','octagon','pentagon','quadrant','semicircle','triangle','unicycle','unilateral','unify','universe'] },
{ grade:5, week:22, theme:'Greek Prefixes — Opposition & Negation',
  words:['agnostic','amoral','anaerobic','anarchy','anonymous','anti-inflammatory','antibiotic','antidote','antipathy','antiseptic','antithesis','apathy','atheism','atheist','atypical','dysfunctional','malnutrition','misanthrope','misogyny','pseudonym'] },
{ grade:5, week:23, theme:'Borrowed Words — Science & Technology',
  words:['algorithm','avatar','bandwidth','byte','carcinogen','chromosome','cliché','database','dinosaur','ecology','forensics','genome','internet','laser','prototype','quantum','quasar','tsunami','typhoon','vaccine'] },
{ grade:5, week:24, theme:'Borrowed Words — Arts & Culture',
  words:['album','ballet','bazaar','boutique','buffet','camouflage','carnival','cinema','genre','guitar','hurricane','machete','maestro','pajamas','panorama','piano','safari','soprano','sushi','yoga'] },
{ grade:5, week:25, theme:'Civic & Political Science',
  words:['amendment','bureaucracy','capitalism','citizenship','communism','constitution','democracy','electoral','executive','fascism','federalism','government','humanitarian','judiciary','legislation','liberalism','oligarchy','parliament','republic','socialism'] },
{ grade:5, week:26, theme:'Economics & Business',
  words:['bankruptcy','capitalism','commodity','competition','consumer','corporation','currency','deficit','depreciation','economics','employment','entrepreneur','expenditure','investment','monopoly','productivity','recession','revenue','shareholder','tariff'] },
{ grade:5, week:27, theme:'Psychology & Human Behavior',
  words:['aggression','altruism','ambiguity','anxiety','cognition','conformity','consciousness','empathy','esteem','hypothesis','inhibition','instinct','motivation','narcissism','perception','personality','prejudice','psychology','rationalize','subconscious'] },
{ grade:5, week:28, theme:'Words Often Confused or Misspelled',
  words:['acceptable','accessible','accommodate','acquaintance','conscience','conscious','deceive','definitely','eloquence','exaggerate','grammar','guarantee','harass','irrelevant','judgment','liaison','maintenance','occurrence','perseverance','supersede'] },
{ grade:5, week:29, theme:'Vocabulary — Precision & Nuance',
  words:['aberrant','affinity','alleviate','ambiguous','apprehensive','benevolent','candid','concise','conscientious','corroborate','delineate','elusive','ephemeral','exacerbate','futile','inadvertent','magnanimous','ostensible','perfunctory','ubiquitous'] },
{ grade:5, week:30, theme:'Spelling Bee Challenge — Grade 5',
  words:['acquiesce','archipelago','camaraderie','clandestine','diaphanous','ecclesiastical','fiduciary','idiosyncrasy','labyrinthine','loquacious','mercurial','nonchalant','obsequious','perspicacious','quintessential','recalcitrant','sagacious','serendipity','soliloquy','sycophant'] },

// ══════════════════════════════════════════════════════
// GRADE 6  (20 words/week, 20 weeks)
// Two Bee + Three Bee words organized by vocational theme
// ══════════════════════════════════════════════════════

{ grade:6, week:1,  theme:'Science — Biology & Medicine',
  words:['abiogenesis','adipose','anesthetic','arrhythmia','autopsy','carcinoma','cytology','deficiency','dermatology','diagnosis','epidemiology','hematology','hypertension','immunology','leukemia','pathogen','pharmacology','physiology','prognosis','thrombosis'] },
{ grade:6, week:2,  theme:'Science — Chemistry & Physics',
  words:['amalgamate','covalent','crystallography','deliquescent','effervescence','electrolysis','equilibrium','fluorescence','galvanism','isotope','luminescence','molecule','oscillation','photolysis','polymerization','precipitate','quantum','refraction','sublimation','thermodynamics'] },
{ grade:6, week:3,  theme:'Science — Earth & Astronomy',
  words:['accretion','aphelion','astronomical','atmospheric','axial','chromosphere','circumference','constellation','cosmology','eclipse','ephemeris','geological','gravitational','hemisphere','hydrothermal','ionosphere','luminosity','magnetosphere','perihelion','spectroscopy'] },
{ grade:6, week:4,  theme:'Engineering & Architecture',
  words:['acoustical','aerodynamic','cantilevered','compressive','corrosion','electromagnetic','fortification','hydraulic','infrastructure','kinematic','load-bearing','masonry','mechanical','metallurgy','pneumatic','seismic','structural','tensile','thermodynamic','trapezoidal'] },
{ grade:6, week:5,  theme:'Law & Government',
  words:['acquittal','appellate','arbitration','circumscribe','coercion','constitutional','de facto','defamation','eminent domain','fiduciary','indemnity','injunction','jurisdiction','legislation','misdemeanor','negligence','ordinance','precedent','subpoena','tort'] },
{ grade:6, week:6,  theme:'Economics & Finance',
  words:['amortization','arbitrage','collateral','consortium','contractual','depreciation','diversification','fiduciary','globalization','hedge fund','indemnification','inflation','intermediary','liquidation','macroeconomic','microeconomic','monopolistic','oligopoly','securitization','valuation'] },
{ grade:6, week:7,  theme:'Healthcare & Medicine',
  words:['analgesia','anesthesiology','cardiovascular','contraindication','diagnosis','differential','dosimetry','electrocardiogram','endocrinology','etiology','gastrointestinal','hematology','immunosuppression','neurosurgery','orthopedic','pharmacokinetics','psychiatry','radiology','rehabilitation','symptomatology'] },
{ grade:6, week:8,  theme:'Business & Management',
  words:['accountability','amalgamation','benchmarking','bureaucracy','conglomerate','entrepreneurship','franchise','globalization','hierarchy','incorporation','infrastructure','innovation','liquidation','logistics','managerial','procurement','restructuring','shareholder','stakeholder','synergy'] },
{ grade:6, week:9,  theme:'Arts — Music & Performance',
  words:['accompaniment','allegretto','arpeggio','choreography','chromatic','contrapuntal','diminuendo','dissonance','fortissimo','harmonics','improvisation','leitmotif','melismatic','obligato','orchestration','pizzicato','polyphonic','rubato','syncopation','tremolo'] },
{ grade:6, week:10, theme:'Arts — Visual & Literary',
  words:['abstraction','anachronism','anthropomorphic','caricature','chiaroscuro','colloquial','connotation','denouement','diatribe','didactic','epigrammatic','expressionism','genre','hyperbole','juxtaposition','metaphorical','naturalism','neoclassical','surrealism','symbolism'] },
{ grade:6, week:11, theme:'Education & Academia',
  words:['accreditation','baccalaureate','bibliography','curriculum','dissertation','epistemology','etymology','heuristic','hypothesis','interdisciplinary','pedagogical','phenomenology','prerequisites','qualitative','quantitative','rhetoric','scholarship','semantics','syllabus','taxonomy'] },
{ grade:6, week:12, theme:'Military & Defense',
  words:['ammunition','armistice','battalion','bombardment','camouflage','capitulation','counterintelligence','decommission','demilitarized','fortification','guerrilla','incendiary','infiltration','insurgency','reconnaissance','regiment','sabotage','surveillance','tactical','tribunal'] },
{ grade:6, week:13, theme:'Religion & Philosophy',
  words:['agnosticism','anthropomorphism','asceticism','atheism','calvinism','deontology','ecclesiastical','enlightenment','eschatology','existentialism','hermeneutics','humanism','iconoclasm','nihilism','ontology','pantheism','phenomenology','pragmatism','stoicism','utilitarianism'] },
{ grade:6, week:14, theme:'Politics & International Relations',
  words:['annexation','bureaucratic','coalition','colonialism','communism','constitutional','diplomacy','disenfranchise','geopolitical','globalization','hegemony','imperialism','multilateral','nationalism','parliamentary','referendum','sovereignty','totalitarianism','unilateral','xenophobia'] },
{ grade:6, week:15, theme:'Technology & Computing',
  words:['algorithm','authentication','cryptography','cybersecurity','decentralized','distributed','encryption','firmware','infrastructure','integration','microprocessor','nanotechnology','network','parallelization','periphery','programming','quantum','semiconductor','virtualization','visualization'] },
{ grade:6, week:16, theme:'Psychology & Sociology',
  words:['acculturation','altruism','anthropological','assimilation','behavioral','cognition','collectivism','conformity','determinism','discrimination','empiricism','ethnocentrism','individualism','institutionalization','marginalization','narcissism','oppression','prejudice','psychological','socialization'] },
{ grade:6, week:17, theme:'Sports & Athletics',
  words:['acceleration','aerobics','biomechanics','cardiovascular','cardiomuscular','choreography','coordination','dehydration','endurance','flexibility','hypertrophy','kinesiologist','metabolism','nutrition','physiology','proprioception','rehabilitation','resilience','stamina','thermogenesis'] },
{ grade:6, week:18, theme:'Culinary Arts & Food Science',
  words:['alimentation','appetizer','ascorbic','beurre blanc','caramelization','chlorophyll','confectionery','dehydration','emulsification','fermentation','gastronomy','lacto-fermented','macronutrient','micronutrient','nitrification','pasteurization','probiotics','sterilization','thermolabile','yeast'] },
{ grade:6, week:19, theme:'Fashion & Textiles',
  words:['accessorize','aesthetic','asymmetrical','avant-garde','bourgeois','brocade','cashmere','contemporary','couture','embroidery','fashionable','haute couture','inimitable','minimalism','monochromatic','ornamental','silhouette','sophisticated','tailoring','wearable'] },
{ grade:6, week:20, theme:'Spelling Bee Challenge — Grade 6',
  words:['anagnorisis','appoggiatura','cymotrichous','feuilleton','guerdon','knaidel','logorrhea','noctambulism','plenipotentiary','psammophile','quincunx','schwarmerei','stichomythia','succedaneum','syzygy','tergiversation','ursprache','weltanschauung','amphigory','covellite'] },

// ══════════════════════════════════════════════════════
// GRADE 7  (22 words/week, 20 weeks)
// Two Bee + Three Bee vocational themes
// ══════════════════════════════════════════════════════

{ grade:7, week:1,  theme:'Neuroscience & Cognitive Science',
  words:['acetylcholine','amygdala','axon','brainstem','cerebellum','cerebral','cognition','cortex','dendrite','dopaminergic','electroencephalogram','hippocampus','hypothalamus','limbic','melanocortin','myelin','neurotransmitter','neuroplasticity','prefrontal','proprioception','serotonin','synaptic'] },
{ grade:7, week:2,  theme:'Genetics & Molecular Biology',
  words:['adenine','allele','biochemistry','biosynthesis','chromosome','codon','cytosine','deoxyribose','diploid','electrophoresis','enzyme','genotype','guanine','haploid','heritability','mitochondrial','mitosis','mRNA','nucleotide','phenotype','ribonucleic','thymine'] },
{ grade:7, week:3,  theme:'Quantum Physics & Advanced Science',
  words:['antimatter','bosons','chromodynamics','complementarity','electroweak','entanglement','fermions','Heisenberg','Higgs','interferometry','ionization','Lagrangian','lepton','nonlinearity','photovoltaic','quark','relativistic','renormalization','spacetime','superposition','uncertainty','wavefunction'] },
{ grade:7, week:4,  theme:'Architecture & Urban Planning',
  words:['arcology','brutalism','colonnade','deconstructivism','fenestration','functionalism','geodesic','infrastructure','interstitial','masonry','metropolitan','minimalism','modular','postmodernism','prefabricated','rehabilitation','retrofitting','revitalization','sustainable','tessellation','transeptual','vernacular'] },
{ grade:7, week:5,  theme:'Advanced Law — Constitutional & International',
  words:['adjudication','adversarial','appellate','arbitration','certiorari','circumvention','codification','constitutional','extraterritorial','habeas corpus','indemnification','injunctive','jurisprudence','mens rea','negligence','nolo contendere','promissory','restitution','subrogation','tortfeasor','unilateral','venire'] },
{ grade:7, week:6,  theme:'Finance — Investment & Trading',
  words:['amortization','annualized','arbitrageur','benchmark','capitalization','collateralized','commodity','counterparty','derivative','divestiture','equitization','fiduciary','hedging','leveraged','liquidity','macroeconomic','microeconomic','overcapitalization','quantitative','rebalancing','securitization','underwriter'] },
{ grade:7, week:7,  theme:'Political Science — Theory & Systems',
  words:['anarchism','bicameralism','bureaucratization','confederalism','constitutionalism','corporatism','cosmopolitanism','deliberative','disenfranchisement','egalitarianism','federalism','geopolitics','hegemony','libertarianism','majoritarianism','meritocracy','nationalism','pluralism','populism','technocracy','totalitarianism','utilitarianism'] },
{ grade:7, week:8,  theme:'Philosophy — Ethics & Metaphysics',
  words:['absurdism','altruism','anthropomorphism','categorical','consequentialism','determinism','dialectics','dualism','empiricism','epistemology','existentialism','hedonism','humanism','materialism','metaphysics','nihilism','ontology','relativism','solipsism','stoicism','teleology','utilitarianism'] },
{ grade:7, week:9,  theme:'Classical Linguistics & Etymology',
  words:['anaphora','cataphora','circumlocution','deictic','euphemism','heteroglossic','homophony','idiolect','isogloss','morphophonology','orthography','paleography','parallelism','parenthetical','periphrasis','phonetics','pragmatics','prosody','semantics','sociolinguistics','syntax','tautology'] },
{ grade:7, week:10, theme:'Literary Criticism & Theory',
  words:['allegory','anachronism','anthropocentric','archetypes','bildungsroman','catharsis','chiasmus','deconstruction','defamiliarization','denouement','diegesis','didacticism','ekphrasis','epistolary','intertextuality','metafiction','mimesis','neologism','postcolonial','structuralism','tragicomedy','vraisemblance'] },
{ grade:7, week:11, theme:'Environmental Science — Climate',
  words:['acidification','albedo','anthropocene','bioaccumulation','biome','carbon sequestration','cryosphere','desertification','eutrophication','geosphere','hydrological','ionosphere','methane','nitrification','photochemical','stratospheric','biogeochemical','thermocline','thermosphere','transpiration','troposphere','volatilization'] },
{ grade:7, week:12, theme:'Advanced Medicine — Specialty Fields',
  words:['anaphylaxis','bacteriophage','cardiomyopathy','chemoradiotherapy','contraindication','cryosurgery','cytotoxic','dialysis','endocrinopathy','gastroparesis','immunosuppression','laparoscopy','neurodegenerative','neuropsychiatric','oncological','pharmacogenomics','plasmapheresis','prognosis','radiosurgery','sarcoidosis','strabismus','thromboembolism'] },
{ grade:7, week:13, theme:'Materials Science & Engineering',
  words:['allotrope','amorphous','anisotropy','brittleness','capacitance','cathodic','cermet','conductivity','crystallography','dielectric','elasticity','electromagnetic','ferromagnetic','heterogeneous','hydrophobic','isotropic','luminescent','nanotube','piezoelectric','plasticity','tensile','thermoplastic'] },
{ grade:7, week:14, theme:'Economics — Macroeconomics',
  words:['aggregate','arbitrage','autarky','behavioral','comparative advantage','commoditization','deflation','disinflation','econometrics','externality','fiscal','hyperinflation','Keynesian','laissez-faire','liquidity trap','macroprudential','Marxist','mercantilism','microeconomics','monetarism','stagflation','systemic'] },
{ grade:7, week:15, theme:'Advanced Technology — AI & Robotics',
  words:['actuator','algorithm','autonomous','backpropagation','convolutional','cybernetics','eigenvalue','encoder','heuristic','inference','Kalman','kinematic','latency','LIDAR','macrostate','microstate','neural','optimization','probabilistic','quadratic','reinforcement','topology'] },
{ grade:7, week:16, theme:'Music Theory & Ethnomusicology',
  words:['arpeggiation','bitonality','cadence','contrapuntal','diatonicism','ethnomusicology','expressionism','fundamentalism','heterophony','improvisation','intonation','modulation','musicology','neoclassicism','orchestration','pentatonic','polyphony','retrograde','serialism','sonata','timbre','tonality'] },
{ grade:7, week:17, theme:'Forensic Science',
  words:['anthropometry','autoradiography','ballistics','chromatography','criminologist','deoxyribonucleic','electrophoresis','entomology','fingerprinting','forensic','luminescence','microscopy','pathology','phenotype','polygraph','rigor mortis','serology','spectroscopy','surveillance','toxicology','ultraviolet','verification'] },
{ grade:7, week:18, theme:'Advanced History — World Civilizations',
  words:['acculturation','amalgamation','anthropological','bureaucratization','colonialism','confucianism','desacralization','diaspora','egalitarianism','enlightenment','feudalism','hellenistic','historiography','imperialism','industrialization','mercantilism','neocolonialism','postcolonialism','proletarianization','reformation','secularization','syncretism'] },
{ grade:7, week:19, theme:'Advanced Words — Greek & Latin Roots',
  words:['agglomerate','ambidextrous','antithetical','bibliophile','cacophonous','circumspection','contiguous','diaphanous','ecclesiastical','ephemeral','equinoctial','hagiography','heterogeneous','loquacious','melancholic','misanthrope','omnipotent','perspicacious','sesquipedalian','sycophantic','tautological','xenophilic'] },
{ grade:7, week:20, theme:'Spelling Bee Challenge — Grade 7',
  words:['appoggiatura','cymotrichous','feuilleton','guerdon','knaidel','logorrhea','noctambulism','plenipotentiary','psammophile','quincunx','schwarmerei','stichomythia','succedaneum','syzygy','tergiversation','ursprache','weltanschauung','amphigory','anagnorisis','covellite','chiaroscuro','schadenfreude'] },

// ══════════════════════════════════════════════════════
// GRADE 8  (25 words/week, 20 weeks)
// Three Bee championship words by theme
// ══════════════════════════════════════════════════════

{ grade:8, week:1,  theme:'Advanced Biology & Biochemistry',
  words:['acetylcholinesterase','adenosine triphosphate','allosteric','apoenzyme','autoimmunity','bioluminescence','chemosynthesis','chylomicron','cyanobacteria','deoxyribonucleoprotein','endocytosis','fermentation','hematopoiesis','homeostasis','hydrolase','immunoglobulin','isomerism','lysosome','oxidoreductase','peroxidase','phospholipid','plasmolysis','ribonucleoprotein','transcription','zymogen'] },
{ grade:8, week:2,  theme:'Advanced Chemistry — Organic & Inorganic',
  words:['acetaldehyde','acylation','aldehydic','alicyclic','benzaldehyde','carboxylic','chromatographic','diastereomers','disproportionation','electrophilic','enantioselectivity','heterocyclic','hydrolysis','isomerization','nucleophilic','polymerization','racemization','rearrangement','stereoisomers','stoichiometry','sublimation','titration','valency','voltammetry','zwitterion'] },
{ grade:8, week:3,  theme:'Advanced Physics — Quantum & Relativity',
  words:['annihilation','Bose-Einstein','bremsstrahlung','chromodynamics','Compton scattering','dielectric','eigenfunction','electroweak','entanglement','Hamiltonian','Heisenberg','Hubble','ionization','Josephson','Lagrangian','magnetohydrodynamics','photovoltaic','positron','renormalization','Schrödinger','spacetime','superconductor','thermalization','Zeno','wavefunction'] },
{ grade:8, week:4,  theme:'Advanced Mathematics',
  words:['asymptotic','automorphism','bijective','cardinality','cofactor','commutative','congruence','contrapositive','covariant','determinant','diffeomorphism','eigenvalue','epimorphism','homeomorphism','idempotent','isomorphism','manifold','monomorphism','nilpotent','orthogonality','permutation','probabilistic','quadrature','surjective','topological'] },
{ grade:8, week:5,  theme:'Advanced Law — Jurisprudence & International',
  words:['adjudication','adversarial','amicus curiae','appellate','certiorari','comity','constitutional','covenanting','customary','defamation','eminent domain','estoppel','exculpatory','extraterritoriality','habeas corpus','inculpatory','indemnification','jurisprudence','nolo contendere','peremptory','promissory','restitution','subrogation','tortfeasor','venire'] },
{ grade:8, week:6,  theme:'Advanced Economics & Econometrics',
  words:['autoregressive','cointegration','countercyclical','deflator','disinflation','econometrics','externalities','Giffen','heteroscedasticity','hyperinflation','Keynesian','Laffer','laissez-faire','liquidity','macroprudential','mercantilism','monetarism','monopsony','oligopolistic','paternalism','prodigality','Ricardian','stagflation','systemic','Walrasian'] },
{ grade:8, week:7,  theme:'Advanced Political Science & Diplomacy',
  words:['anarchy','balance of power','bicameralism','confederation','constructivism','cosmopolitanism','devolution','egalitarianism','federalism','geopolitics','hegemony','interventionism','irredentism','Machiavellianism','majoritarianism','multilateralism','nationalism','neorealism','parliamentarism','populism','realpolitik','sovereignty','technocracy','unilateralism','utilitarianism'] },
{ grade:8, week:8,  theme:'Advanced Philosophy',
  words:['a priori','antinomy','apophatic','cartesianism','categorical imperative','consequentialism','deontological','determinism','dialectical','empiricism','epistemology','existentialism','hermeneutics','Kantian','noumenon','ontological','panentheism','phenomenology','pragmatism','rationalism','relativism','scholasticism','solipsism','teleology','transcendentalism'] },
{ grade:8, week:9,  theme:'Advanced Literature & Rhetoric',
  words:['anachronism','antanaclasis','anticlimactic','anthropomorphism','bildungsroman','catachresis','chiasmus','circumlocution','deconstruction','defamiliarization','diegesis','ekphrasis','epistolary','heteroglossia','intertextuality','irredentism','metatextual','mimesis','narratology','neologism','postcolonialism','prolepsis','structuralism','tragicomedy','vraisemblance'] },
{ grade:8, week:10, theme:'Linguistics & Language Theory',
  words:['affrication','allomorph','alveolar','anthroponymy','complementary','diglossic','dysphemism','euphemism','hapax legomenon','heteroglossia','hypercorrection','isogloss','morphophonology','orthography','paleography','palatalization','phoneme','pragmatics','prosody','semantics','sociolinguistics','substratic','syncope','toponymy','velarity'] },
{ grade:8, week:11, theme:'Advanced Medicine — Rare & Specialized',
  words:['achondroplasia','agammaglobulinemia','anaphylaxis','antiphospholipid','bacteremia','cardiomyopathy','cryptococcosis','dermatomyositis','encephalopathy','fibromyalgia','hemochromatosis','hypercholesterolemia','immunodeficiency','malignancy','mastocytosis','mesothelioma','neurofibroma','onchocerciasis','pharmacogenomics','polycythemia','rhabdomyolysis','sarcoidosis','thrombocytopenia','vasculitis','zoonosis'] },
{ grade:8, week:12, theme:'Materials Science & Nanotechnology',
  words:['amorphous','anisotropy','bimetallic','capacitance','cathodic','cermet','conductivity','crystallography','dielectric','elastomer','electromigration','ferromagnetic','fullerene','hydrophobic','isotropic','luminescent','magnetorheological','nanotube','piezoelectric','plasticity','polymorph','rheology','superconductor','tensile','thermoplastic'] },
{ grade:8, week:13, theme:'Advanced Neuroscience & Psychology',
  words:['acetylcholine','amygdaloid','axiomatic','cerebellum','chemoreceptor','cognitivism','confabulation','corticotropin','cryptomnesia','default mode','dopaminergic','electroencephalograph','ganglion','hippocampus','hypothalamic','metacognition','mnemonic','neurogenesis','neuroplasticity','psychodynamic','serotonergic','synaptogenesis','thalamus','vesicular','volumetric'] },
{ grade:8, week:14, theme:'Environmental & Climate Science',
  words:['acidification','albedo','anthropocene','bioaccumulation','biogeochemical','carbon sequestration','cryosphere','desertification','eutrophication','geochemical','glaciological','hydrological','methane','nitrification','photochemical','stratospheric','thermocline','thermohaline','troposphere','turbidity','ultraviolet','verifiable','volatilization','zoonosis','zooplankton'] },
{ grade:8, week:15, theme:'Advanced Computing & AI',
  words:['adversarial','backpropagation','Bayesian','bottleneck','convolutional','cybernetics','deep learning','eigendecomposition','encoder','ensemble','generalization','gradient','hyperparameter','inference','instantiation','interpolation','latent space','LSTM','manifold','multimodal','overfitting','probabilistic','quantization','recurrent','stochastic'] },
{ grade:8, week:16, theme:'Advanced History — Theory & Historiography',
  words:['acculturation','amalgamation','anticolonialism','archaeography','chronological','decolonization','determinism','empiricism','ethnocentrism','feudalization','hegemony','historicism','historiography','imperialism','industrialism','Marxism','nationalism','orientalism','postcolonialism','presentism','primitivism','proletarianization','relativism','secularization','syncretism'] },
{ grade:8, week:17, theme:'Advanced Music Theory',
  words:['atonality','bitonality','cadential','contrapuntal','dodecaphonic','enharmonic','ethnomusicology','expressionism','hexatonic','improvisation','inversional','modulation','musicology','neoclassicism','orchestration','palindrome','pentatonic','polyphony','retrograde','serialism','stochastic','tetrachord','timbre','tonality','trichord'] },
{ grade:8, week:18, theme:'Advanced Arts — Visual & Architecture',
  words:['abstraction','anachronism','anthropocentric','arcology','avant-garde','brutalism','chiaroscuro','deconstructivism','defamiliarization','ekphrasis','expressionism','fenestration','functionalism','geodesic','impressionism','juxtaposition','minimalism','neoclassicism','palimpsest','postmodernism','prefabricated','surrealism','symbolism','tessellation','vernacular'] },
{ grade:8, week:19, theme:'Championship Vocabulary — Obscure & Technical',
  words:['amphigory','anagnorisis','appoggiatura','cymotrichous','feuilleton','guerdon','hapax','knaidel','logorrhea','noctambulism','plenipotentiary','psammophile','quincunx','schwarmerei','sesquipedalian','stichomythia','succedaneum','syzygy','tergiversation','ursprache','weltanschauung','xenogenesis','zoetrope','zymurgy','zugzwang'] },
{ grade:8, week:20, theme:'Final Spelling Bee Championship',
  words:['abiogenesis','anthropophagi','bibliophilia','cacoethes','cymotrichous','diaphanous','ecclesiastical','feuilleton','hapax legomenon','idiosyncrasy','logorrhea','magniloquent','narcissism','obsequious','perspicacious','quixotic','recalcitrant','sesquipedalian','tergiversation','ubiquitous','verisimilitude','weltanschauung','xenophilia','zoetrope','zugzwang'] },

];

module.exports = { WEEKLY };
